### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [oruchkin/Async_API_sprint_1#41]
Все отлично! Рекомендации ниже:
1. С развитием проекта в тестах фикстур будет все больше и больше, и их нужно систематизировать. Можно вынести в отдельный файл (затем добавлять другие файлы, логически разделяя их) и тем самым облегчим conftest.py. Для этого в conftest.py есть [pytest_plugins](https://docs.pytest.org/en/latest/how-to/fixtures.html#using-fixtures-from-other-projects)
2. [Скобки](https://github.com/oruchkin/Async_API_sprint_1/blob/486d7a6756a758b26b5df4fce117e8c1a11f11a4/api/tests/functional/src/conftest.py#L95) лишние
3. Не используйте прямое указание кодов ответов сервера (200, 400 и т.д.), применяйте [http.HTTPStatus](https://docs.python.org/3/library/http.html#http.HTTPStatus). Дело в том, что в коде проекта найти HTTPStatus.OK значительно проще чем найти 200, кроме того этим мы защитимся от опечаток, да и читаемость кода повысится.
4. В src/api/v1 много раз встречается вот такая конструкция в параметрах методов:
      ```python
      page_number: int = Query(1, description="Page number", ge=1),
      page_size: int = Query(10, description="Page size", ge=1, le=100),
      ```
      Можно попробовать вынести эту пару в отдельный класс, какой-нибудь PaginatedParams, инжектить его в качестве зависимости в параметры методов и работать с ними как с объектом. Т.о. параметры пагинации будут в одном месте и при необходимости легко будет их изменить сразу и везде.
5. [можно лучше] Старайтесь больше использовать абстрактные классы в работе. В ваших сервисах у вас явно используется класс AsyncElasticsearch в типизации, а если со временем перейдем на другой сервис полнотекстового поиска, то придетс менять код приложения много где. У меня есть небольшой набросок, https://github.com/RomanAVolodin/FastAPI_DI/tree/feature/DI, вся работа идет с абстрактными классами, которые выступают в роли интерфейсов, а сопоставление абстрактного класса и его реализации происходит в одном месте, и если будет принято решение использовать другую реализацию, то достуточно будет внести изменение в одном месте кода.

**Comment by oruchkin** [comment]
1. в процессе
2. в процессе
3. в процессе
4. сделано
